# Generated by Django 3.1.5 on 2021-01-11 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.IntegerField()),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('first_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.rubric')),
            ],
        ),
    ]
